# Generated by Django 5.0.6 on 2024-07-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=128)),
                ("nickname", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
