# Generated by Django 5.0.6 on 2024-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registr", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
