# Generated by Django 5.0.6 on 2024-07-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_imagesinproduct_product_product_category"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="makinganorder",
            name="status",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.status",
            ),
        ),
        migrations.AddField(
            model_name="productinbasket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.makinganorder",
            ),
        ),
        migrations.AddField(
            model_name="productinbasket",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.product",
            ),
        ),
    ]
