# Generated by Django 5.0.6 on 2024-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_makinganorder_status_productinbasket_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinbasket",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="productinbasket",
            name="total_price",
            field=models.FloatField(default=1),
        ),
    ]
