# Generated by Django 5.0.6 on 2024-07-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_productinbasket_quantity_productinbasket_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinbasket",
            name="price_one_product",
            field=models.FloatField(default=0),
        ),
    ]
