# Generated by Django 5.0.6 on 2024-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_productinbasket_price_one_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinbasket",
            name="price_one_product",
            field=models.FloatField(default=1),
        ),
    ]
