# Generated by Django 5.0.6 on 2024-07-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagesinproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.categoryproduct",
            ),
        ),
    ]
